about/urls.py
from django.urls import path
from . import views
app_name = 'about'

urlpatterns =[
    path('',views.index,name='index'),


]

appetizer/urls.py
from django.urls import path
from . import views

app_name = 'appetizer'


urlpatterns =[
    path('',views.index,name='index'),



]

btre/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('appetizer.urls',namespace='appetizer')),
    path('about/',include('about.urls',namespace='about')),
    path('menu/',include('menu.urls',namespace='menu')),
    path('app-contact/',include('contact.urls',namespace='contact')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'

urlpatterns =[
    path('',views.index,name='contact'),




]

menu/urls.py
from django.urls import path
from . import views
app_name = 'menu'

urlpatterns =[
    path('',views.menu_det,name='menu'),




]

about/models.py
from django.db import models

# Create your models here.

class MyChefs(models.Model):
    name = models.CharField(max_length=90)
    name_jop = models.CharField(max_length=90)
    bio  = models.TextField()
    social_media_twitter = models.URLField(default='#',null=True,blank=True)
    social_media_instagram = models.URLField(default='#',null=True,blank=True)
    social_media_facebook = models.URLField(default='#',null=True,blank=True)
    social_media_google = models.URLField(default='#',null=True,blank=True)
    img = models.ImageField(upload_to='about/chefs',null=True,blank=True)

    def __str__(self):
        return self.name

appetizer/models.py
from django.db import models

# Create your models here.


class Slider_title(models.Model):
    title = models.CharField(max_length=200)
    slider_img = models.ImageField(upload_to='slider_img')


    def __str__(self):
        return self.title


class Make_Reservation(models.Model):
    name = models.CharField(max_length=150)
    email= models.EmailField()
    phone = models.IntegerField()
    date = models.CharField(max_length=50)
    time = models.TimeField()
    how_meny_person = models.CharField(max_length=20)


    def __str__(self):
        return self.name

class HappyCustomer(models.Model):
    name = models.CharField(max_length=300)
    img = models.ImageField(upload_to='cust_img')
    bio = models.TextField()
    cust_type = models.CharField(max_length=200)



    def __str__(self):
        return self.name

contact/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models

about/views.py
from django.shortcuts import render
from . import models
from appetizer.models import HappyCustomer
# Create your views here.



def index(request):
    chefs = models.MyChefs.objects.all()
    customers = HappyCustomer.objects.all()

    context = {
        'chefs':chefs,
        'customers':customers,

    }
    return render(request,'about.html',context)

appetizer/views.py
from django.shortcuts import render,get_object_or_404
from . import models
from django.http import HttpResponseRedirect
# Create your views here.


def index(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        date = request.POST['date']
        time = request.POST['time']
        person = request.POST['person']
        make_reservation = models.Make_Reservation()
        make_reservation.name=name
        make_reservation.email=email
        make_reservation.phone=phone
        make_reservation.date=date
        make_reservation.time=time
        make_reservation.how_meny_person=person
        make_reservation.save()
        return HttpResponseRedirect('/')
    else:
        customers = models.HappyCustomer.objects.all()
        slider = models.Slider_title.objects.all()
        context = {
            'customers': customers,
            'slider':slider,

        }
    return render(request,'index.html',context)

contact/views.py
from django.shortcuts import render

# Create your views here.




def index(request):
    return render(request,'contact.html',{})

menu/views.py
from django.shortcuts import render
from appetizer.models import Make_Reservation

# Create your views here.




def menu_det(request):
    return render(request,'menu.html',{})







def make_respons(request):#name email phone date time person
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        date = request.POST['date']
        time = request.POST['time']
        person = request.POST['person']
        make_reservation = Make_Reservation()
        make_reservation.name=name
        make_reservation.email=email
        make_reservation.phone=phone
        make_reservation.date=date
        make_reservation.time=time
        make_reservation.how_meny_person=person
        make_reservation.save()
        return HttpResponse('Done')

about/templates/about.html
{%extends 'base.html'%}
{% load static %}
{% block content %}

    
    <section class="hero-wrap hero-wrap-2" style="background-image: url('{%static 'images/bg_3.jpg'%}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">About</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>About <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>
	

		<section class="ftco-section ftco-wrap-about ftco-no-pb">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-sm-10 wrap-about ftco-animate text-center">
	          <div class="heading-section mb-4 text-center">
	          	<span class="subheading">About</span>
	            <h2 class="mb-4">Appetizer Restaurant</h2>
	          </div>
						<p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word "and" and the Little Blind Text should turn around and return to its own, safe country. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>


	  					</a>
						</div>
					</div>
				</div>
			</div>
		</section>

		
		<section class="ftco-section ftco-counter img" id="section-counter" style="background-image: url({%static 'images/bg_4.jpg'%});" data-stellar-background-ratio="0.5">
		<!-- <section class="ftco-section ftco-counter img ftco-no-pt" id="section-counter"> -->
    	<div class="container">
    		<div class="row d-md-flex align-items-center justify-content-center">
    			<div class="col-lg-10">
    				<div class="row d-md-flex align-items-center">
		          <div class="col-md d-flex justify-content-center counter-wrap ftco-animate">
		            <div class="block-18">
		              <div class="text">
		                <strong class="number" data-number="18">0</strong>
		                <span>Years of Experienced</span>
		              </div>
		            </div>
		          </div>
		          <div class="col-md d-flex justify-content-center counter-wrap ftco-animate">
		            <div class="block-18">
		              <div class="text">
		                <strong class="number" data-number="15000">0</strong>
		                <span>Happy Customers</span>
		              </div>
		            </div>
		          </div>
		          <div class="col-md d-flex justify-content-center counter-wrap ftco-animate">
		            <div class="block-18">
		              <div class="text">
		                <strong class="number" data-number="100">0</strong>
		                <span>Menus</span>
		              </div>
		            </div>
		          </div>
		          <div class="col-md d-flex justify-content-center counter-wrap ftco-animate">
		            <div class="block-18">
		              <div class="text">
		                <strong class="number" data-number="20">0</strong>
		                <span>Staffs</span>
		              </div>
		            </div>
		          </div>
	          </div>
          </div>
        </div>
    	</div>
    </section>

		<section class="ftco-section bg-light">
			<div class="container">
				<div class="row justify-content-center mb-5 pb-2">
          <div class="col-md-7 text-center heading-section ftco-animate">
          	<span class="subheading">Services</span>
            <h2 class="mb-4">Catering Services</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 d-flex align-self-stretch ftco-animate text-center">
            <div class="media block-6 services d-block">
              <div class="icon d-flex justify-content-center align-items-center">
            		<span class="flaticon-cake"></span>
              </div>
              <div class="media-body p-2 mt-3">
                <h3 class="heading">Birthday Party</h3>
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
              </div>
            </div>      
          </div>
          <div class="col-md-4 d-flex align-self-stretch ftco-animate text-center">
            <div class="media block-6 services d-block">
              <div class="icon d-flex justify-content-center align-items-center">
            		<span class="flaticon-meeting"></span>
              </div>
              <div class="media-body p-2 mt-3">
                <h3 class="heading">Business Meetings</h3>
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
              </div>
            </div>    
          </div>
          <div class="col-md-4 d-flex align-self-stretch ftco-animate text-center">
            <div class="media block-6 services d-block">
              <div class="icon d-flex justify-content-center align-items-center">
            		<span class="flaticon-tray"></span>
              </div>
              <div class="media-body p-2 mt-3">
                <h3 class="heading">Wedding Party</h3>
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
              </div>
            </div>      
          </div>
        </div>
			</div>
		</section>

    
		<section class="ftco-section">
			<div class="container">
				<div class="row justify-content-center mb-5 pb-2">
          <div class="col-md-7 text-center heading-section ftco-animate">
          	<span class="subheading">Chef</span>
            <h2 class="mb-4">Our Master Chef</h2>
          </div>
        </div>	
				<div class="row">
                    {%for chef in chefs%}
					<div class="col-md-6 col-lg-3 ftco-animate">
						<div class="staff">
							<div class="img" style="background-image: url({{chef.img.url}});"></div>
							<div class="text pt-4">
								<h3>{{chef.name}}</h3>
								<span class="position mb-2">{{chef.name_jop}}</span>
								<p>{{chef.bio}}</p>
								<div class="faded">
									<!-- <p>I am an ambitious workaholic, but apart from that, pretty simple person.</p> -->
									<ul class="ftco-social d-flex">
		                <li class="ftco-animate"><a href="{{chef.social_media_twitter}}"><span class="icon-twitter"></span></a></li>
		                <li class="ftco-animate"><a href="{{chef.social_media_facebook}}"><span class="icon-facebook"></span></a></li>
		                <li class="ftco-animate"><a href="{{chef.social_media_google}}"><span class="icon-google-plus"></span></a></li>
		                <li class="ftco-animate"><a href="{{chef.social_media_instagram}}"><span class="icon-instagram"></span></a></li>
		              </ul>
	              </div>

							</div>
						</div>
					</div>
                    {%endfor%}
				</div>
			</div>
		</section>
		
		<!-- <section class="ftco-section testimony-section" style="background-image: url(images/bg_5.jpg);" data-stellar-background-ratio="0.5"> -->
				<section class="ftco-section testimony-section img" style="background-image: url({%static 'images/bg_5.jpg'%});">
			<div class="overlay"></div>
      <div class="container">
        <div class="row justify-content-center mb-5">
          <div class="col-md-7 text-center heading-section ftco-animate">
          	<span class="subheading">Testimony</span>
            <h2 class="mb-4">Happy Customer</h2>
          </div>
        </div>
        <div class="row ftco-animate justify-content-center">
          <div class="col-md-12">
              <div class="carousel-testimony owl-carousel ftco-owl">
                  {%for cust in customers %}
                  <div class="item">
                <div class="testimony-wrap text-center pb-5">
                  <div class="user-img mb-4" style="background-image: url({{cust.img.url}})">
                    <span class="quote d-flex align-items-center justify-content-center">
                      <i class="icon-quote-left"></i>
                    </span>
                  </div>
                  <div class="text p-3">
                    <p class="mb-4">{{cust.bio}}</p>
                    <p class="name">{{cust.name}}</p>
                    <span class="position">{{cust.cust_type}}</span>
                  </div>
                </div>
              </div>
              {%endfor%}
            </div>



          </div>
        </div>
      </div>
    </section>
		

		<section class="ftco-section ftco-no-pt ftco-no-pb">
			<div class="container-fluid px-0">
				<div class="row no-gutters">
					<div class="col-md">
						<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url({%static 'images/insta-1.jpg' %});">
							<span class="ion-logo-instagram"></span>
						</a>
					</div>
					<div class="col-md">
						<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url({%static 'images/insta-2.jpg' %});">
							<span class="ion-logo-instagram"></span>
						</a>
					</div>
					<div class="col-md">
						<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url({%static 'images/insta-3.jpg' %});">
							<span class="ion-logo-instagram"></span>
						</a>
					</div>
					<div class="col-md">
						<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url({%static 'images/insta-4.jpg' %});">
							<span class="ion-logo-instagram"></span>
						</a>
					</div>
					<div class="col-md">
						<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url({%static 'images/insta-5.jpg' %});">
							<span class="ion-logo-instagram"></span>
						</a>
					</div>
				</div>
			</div>
		</section>
{%endblock%}

contact/templates/contact.html
{%extends 'base.html'%}
{% load static %}
{% block content %}


    
    <section class="hero-wrap hero-wrap-2" style="background-image: url({%static 'images/bg_3.jpg'%});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">Contact Us</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Contact <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>
	
		<section class="ftco-section contact-section bg-light">
      <div class="container">
        <div class="row d-flex contact-info">
          <div class="col-md-12 mb-4">
            <h2 class="h4 font-weight-bold">Contact Information</h2>
          </div>
          <div class="w-100"></div>
          <div class="col-md-3 d-flex">
          	<div class="dbox">
	            <p><span>Address:</span> 198 West 21th Street, Suite 721 New York NY 10016</p>
            </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="dbox">
	            <p><span>Phone:</span> <a href="#">+20 01066448428</a></p>
            </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="dbox">
	            <p><span>Email:</span> <a href="#">ehapsamy111@yahoo.com</a></p>
            </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="dbox">
	            <p><span>Website</span> <a href="#">ehapsamy.com</a></p>
            </div>
          </div>
        </div>
      </div>
    </section>
		<section class="ftco-section ftco-no-pt ftco-no-pb contact-section">
			<div class="container">
				<div class="row d-flex align-items-stretch no-gutters">
					<div class="col-md-6 p-5 order-md-last">
						<h2 class="h4 mb-5 font-weight-bold">Contact Us</h2>
						<form action="#">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Name">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Email">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Subject">
              </div>
              <div class="form-group">
                <textarea name="" id="" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>
              </div>
              <div class="form-group">
                <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
              </div>
            </form>
					</div>

				</div>
			</div>
		</div>
        </section>
		
		<section class="ftco-section ftco-no-pt ftco-no-pb">
			<div class="container-fluid px-0">
				<div class="row no-gutters">
					<div class="col-md">
						<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url({%static 'images/insta-1.jpg'%});">
							<span class="ion-logo-instagram"></span>
						</a>
					</div>
					<div class="col-md">
						<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url({%static 'images/insta-2.jpg'%});">
							<span class="ion-logo-instagram"></span>
						</a>
					</div>
					<div class="col-md">
						<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url({%static 'images/insta-3.jpg'%});">
							<span class="ion-logo-instagram"></span>
						</a>
					</div>
					<div class="col-md">
						<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url({%static 'images/insta-4.jpg'%});">
							<span class="ion-logo-instagram"></span>
						</a>
					</div>
					<div class="col-md">
						<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url({%static 'images/insta-5.jpg'%});">
							<span class="ion-logo-instagram"></span>
						</a>
					</div>
				</div>
			</div>
		</section>

{%endblock%}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Appetizer - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Monoton&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Miss+Fajardose&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{%static 'css/open-iconic-bootstrap.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/animate.css'%}">
    
    <link rel="stylesheet" href="{%static 'css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/owl.theme.default.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/magnific-popup.css'%}">

    <link rel="stylesheet" href="{%static 'css/aos.css'%}">

    <link rel="stylesheet" href="{%static 'css/ionicons.min.css'%}">

    <link rel="stylesheet" href="{%static 'css/bootstrap-datepicker.css'%}">
    <link rel="stylesheet" href="{%static 'css/jquery.timepicker.css'%}">

    
    <link rel="stylesheet" href="{%static 'css/flaticon.css'%}">
    <link rel="stylesheet" href="{%static 'css/icomoon.css'%}">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
  </head>
  <body>
 <div class="py-1 bg-black top">
    	<div class="container">
    		<div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
	    		<div class="col-lg-12 d-block">
		    		<div class="row d-flex">
		    			<div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
						    <span class="text">+20  0106 644 8428</span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
						    <span class="text">ehapsamy111@yahoo.com</span>
					    </div>
					    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right justify-content-end">
						    <p class="mb-0 register-link"><span>Open hours:</span> <span>Monday - Sunday</span> <span>8:00AM - 9:00PM</span></p>
					    </div>
				    </div>
			    </div>
		    </div>
		  </div>
    </div>
	  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="index.html">Appetizer</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	        	<li class="nav-item active"><a href="{%url 'appetizer:index'%}" class="nav-link">Home</a></li>
	        	<li class="nav-item"><a href="{%url 'about:index'%}" class="nav-link">About</a></li>
	        	<li class="nav-item"><a href="{%url 'menu:menu'%}" class="nav-link">Menu</a></li>
	          <li class="nav-item"><a href="{%url 'contact:contact'%}" class="nav-link">Contact</a></li>

	        </ul>
	      </div>
	    </div>
	  </nav>
{% block content %}  {%endblock%}
    <footer class="ftco-footer ftco-bg-dark ftco-section">
      <div class="container-fluid px-md-5 px-3">
        <div class="row mb-5">
          <div class="col-md-6 col-lg-3">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Appetizer</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-6 col-lg-3">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Open Hours</h2>
              <ul class="list-unstyled open-hours">
                <li class="d-flex"><span>Monday</span><span>9:00 - 24:00</span></li>
                <li class="d-flex"><span>Tuesday</span><span>9:00 - 24:00</span></li>
                <li class="d-flex"><span>Wednesday</span><span>9:00 - 24:00</span></li>
                <li class="d-flex"><span>Thursday</span><span>9:00 - 24:00</span></li>
                <li class="d-flex"><span>Friday</span><span>9:00 - 02:00</span></li>
                <li class="d-flex"><span>Saturday</span><span>9:00 - 02:00</span></li>
                <li class="d-flex"><span>Sunday</span><span> 9:00 - 02:00</span></li>
              </ul>
            </div>
          </div>
          <div class="col-md-6 col-lg-3">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Newsletter</h2>
            	<p>Far far away, behind the word mountains, far from the countries.</p>
              <form action="#" class="subscribe-form">
                <div class="form-group">
                  <input type="text" class="form-control mb-2 text-center" placeholder="Enter email address">
                  <input type="submit" value="Subscribe" class="form-control submit px-3">
                </div>
              </form>
            </div>
          </div>
            <!--
          <div class="col-md-6 col-lg-3">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Instagram</h2>
              <div class="thumb d-sm-flex">
	            	<a href="#" class="thumb-menu img" style="background-image: url(images/insta-1.jpg);">
	            	</a>
	            	<a href="#" class="thumb-menu img" style="background-image: url(images/insta-2.jpg);">
	            	</a>
	            	<a href="#" class="thumb-menu img" style="background-image: url(images/insta-3.jpg);">
	            	</a>
	            </div>
	            <div class="thumb d-flex">
	            	<a href="#" class="thumb-menu img" style="background-image: url(images/insta-4.jpg);">
	            	</a>
	            	<a href="#" class="thumb-menu img" style="background-image: url(images/insta-5.jpg);">
	            	</a>
	            	<a href="#" class="thumb-menu img" style="background-image: url(images/insta-6.jpg);">
	            	</a>
	            </div>
            </div>
          </div>
            -->
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{%static 'js/jquery.min.js'%}"></script>
  <script src="{%static 'js/jquery-migrate-3.0.1.min.js'%}"></script>
  <script src="{%static 'js/popper.min.js'%}"></script>
  <script src="{%static 'js/bootstrap.min.js'%}"></script>
  <script src="{%static 'js/jquery.easing.1.3.js'%}"></script>
  <script src="{%static 'js/jquery.waypoints.min.js'%}"></script>
  <script src="{%static 'js/jquery.stellar.min.js'%}"></script>
  <script src="{%static 'js/owl.carousel.min.js'%}"></script>
  <script src="{%static 'js/jquery.magnific-popup.min.js'%}"></script>
  <script src="{%static 'js/aos.js'%}"></script>
  <script src="{%static 'js/jquery.animateNumber.min.js'%}"></script>
  <script src="{%static 'js/bootstrap-datepicker.js'%}"></script>
  <script src="{%static 'js/jquery.timepicker.min.js'%}"></script>
  <script src="{%static 'js/scrollax.min.js'%}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{%static 'js/google-map.js'%}"></script>
  <script src="{%static 'js/main.js'%}"></script>
    
  </body>
</html>